name: example
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  consts:
    path: ../
  flutter_motionly: ^1.1.1
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#000009"
  image: assets/splash.png
  android_12:
    image: assets/splash.png